apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-kubearmor-dev-proc-path-block-fromsource
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: kubearmor-dev
  severity: 5
  process:
    matchPaths:
    - path: /bin/date
      fromSource:
      - path: /bin/bash # ubuntu
    - path: /usr/bin/date
      fromSource:
      - path: /usr/bin/bash # centos
  action:
    Block
